arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

translator:
  # key_file: translator_key
  targets:
    - es-ES
    - de
    - fr
    - ja
    - tr
    - uk

  prefer-lang-templates: {
    'fr': 'es-ES',
    'uk': 'de'
  }